// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaCursosOnlineMaoFluent.Data;

#nullable disable

namespace SistemCursosOnlineMapFluent.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20251215224552_incluidoDbSet")]
    partial class incluidoDbSet
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CursoUsuario", b =>
                {
                    b.Property<int>("CursosId")
                        .HasColumnType("int");

                    b.Property<int>("UsuariosId")
                        .HasColumnType("int");

                    b.HasKey("CursosId", "UsuariosId");

                    b.HasIndex("UsuariosId");

                    b.ToTable("CursoUsuario");
                });

            modelBuilder.Entity("SistemaCursosOnlineMaoFluent.Aula", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CursoId")
                        .HasColumnType("int");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("Varchar");

                    b.Property<string>("UrlVideo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("Varchar");

                    b.HasKey("Id")
                        .HasName("PK_Aula_Id");

                    b.HasIndex("CursoId");

                    b.HasIndex("Titulo")
                        .IsUnique();

                    b.ToTable("Aulas");
                });

            modelBuilder.Entity("SistemaCursosOnlineMaoFluent.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("Varchar");

                    b.HasKey("Id")
                        .HasName("FK_Categoria_Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("SistemaCursosOnlineMaoFluent.Models.Avaliacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comentario")
                        .HasMaxLength(250)
                        .HasColumnType("Varchar");

                    b.Property<int>("CursoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataAvaliacao")
                        .HasColumnType("datetime2");

                    b.Property<int>("FK_Avaliacao_CursoId")
                        .HasColumnType("int");

                    b.Property<int>("FK_Avaliacao_UsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("Nota")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_Avaliacao_Id");

                    b.HasIndex("FK_Avaliacao_CursoId");

                    b.HasIndex("FK_Avaliacao_UsuarioId");

                    b.HasIndex("CursoId", "UsuarioId")
                        .IsUnique();

                    b.ToTable("Avaliacoes");
                });

            modelBuilder.Entity("SistemaCursosOnlineMaoFluent.Models.Curso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("Varchar");

                    b.Property<int>("InstrutorId")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("Varchar");

                    b.HasKey("Id")
                        .HasName("PK_Curso_Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("InstrutorId");

                    b.ToTable("Cursos");
                });

            modelBuilder.Entity("SistemaCursosOnlineMaoFluent.Models.Instrutor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("Varchar");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("Varchar");

                    b.HasKey("Id")
                        .HasName("PK_Instrutor_Id");

                    b.ToTable("Instrutores");
                });

            modelBuilder.Entity("SistemaCursosOnlineMaoFluent.Models.Matricula", b =>
                {
                    b.Property<int>("CursoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataMatricula")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("CursoId", "UsuarioId")
                        .HasName("PK_Matricula_Id");

                    b.HasIndex("DataMatricula")
                        .HasDatabaseName("IX_Matricula_DataMatricula");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Matriculas");
                });

            modelBuilder.Entity("SistemaCursosOnlineMaoFluent.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("Varchar");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("Varchar");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK_Usuario_Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("USUARIO", "SCO");
                });

            modelBuilder.Entity("CursoUsuario", b =>
                {
                    b.HasOne("SistemaCursosOnlineMaoFluent.Models.Curso", null)
                        .WithMany()
                        .HasForeignKey("CursosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaCursosOnlineMaoFluent.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuariosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SistemaCursosOnlineMaoFluent.Aula", b =>
                {
                    b.HasOne("SistemaCursosOnlineMaoFluent.Models.Curso", "Curso")
                        .WithMany("Aulas")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CursoAula_CursoId");

                    b.Navigation("Curso");
                });

            modelBuilder.Entity("SistemaCursosOnlineMaoFluent.Models.Avaliacao", b =>
                {
                    b.HasOne("SistemaCursosOnlineMaoFluent.Models.Curso", "Curso")
                        .WithMany("Avaliacoes")
                        .HasForeignKey("FK_Avaliacao_CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaCursosOnlineMaoFluent.Models.Usuario", "Usuario")
                        .WithMany("Avaliacoes")
                        .HasForeignKey("FK_Avaliacao_UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curso");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemaCursosOnlineMaoFluent.Models.Curso", b =>
                {
                    b.HasOne("SistemaCursosOnlineMaoFluent.Categoria", "Categoria")
                        .WithMany("Cursos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_CursoCategoria_CategoriaId");

                    b.HasOne("SistemaCursosOnlineMaoFluent.Models.Instrutor", "Instrutor")
                        .WithMany("Cursos")
                        .HasForeignKey("InstrutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CursoIntrutor_InstrutorId");

                    b.Navigation("Categoria");

                    b.Navigation("Instrutor");
                });

            modelBuilder.Entity("SistemaCursosOnlineMaoFluent.Models.Matricula", b =>
                {
                    b.HasOne("SistemaCursosOnlineMaoFluent.Models.Curso", "Curso")
                        .WithMany("Matriculas")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Matricula_CursoId");

                    b.HasOne("SistemaCursosOnlineMaoFluent.Models.Usuario", "Usuario")
                        .WithMany("Matriculas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Matricula_UsuarioId");

                    b.Navigation("Curso");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemaCursosOnlineMaoFluent.Categoria", b =>
                {
                    b.Navigation("Cursos");
                });

            modelBuilder.Entity("SistemaCursosOnlineMaoFluent.Models.Curso", b =>
                {
                    b.Navigation("Aulas");

                    b.Navigation("Avaliacoes");

                    b.Navigation("Matriculas");
                });

            modelBuilder.Entity("SistemaCursosOnlineMaoFluent.Models.Instrutor", b =>
                {
                    b.Navigation("Cursos");
                });

            modelBuilder.Entity("SistemaCursosOnlineMaoFluent.Models.Usuario", b =>
                {
                    b.Navigation("Avaliacoes");

                    b.Navigation("Matriculas");
                });
#pragma warning restore 612, 618
        }
    }
}
